const { Router } = require("express");
const router = Router();
const restauratnt = require("./modules/restaurantmanagement");
const user = require("./modules/users");
const role = require("./modules/rolemanagement");
const category = require("./modules/categorymanagement");
const staff = require("./modules/staffmanagement");
const cuisine = require("./modules/cuisinemanagement");
const pincode = require("./modules/pincode");
const coupon = require("./modules/couponmanagement");
const masterData = require("./modules/masterDataManagement");
const country = require("./modules/masterDataManagement/country_model/country");
const bank = require("./modules/masterDataManagement/bank_model/bank");
const menu = require("./modules/masterDataManagement/menu_model/menu");
router.use("/api", user);
router.use("/api", role);
router.use("/api", category);
router.use("/api", staff);
router.use("/api", cuisine);
router.use("/api", pincode);
router.use("/api", restauratnt);
router.use("/api", masterData);
router.use("/api", coupon);
module.exports = router;
